<a href="https://colab.research.google.com/github/Aabhiinavvv/Hyperparameter-Tuning-Diabetecs-Prediction-Model-Using-Keras-Tuner/blob/main/diabetesKerasFineTune.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("/content/diabetes.csv")

In [6]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [8]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [10]:
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [11]:
x.shape

(768, 8)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1 )

In [13]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [14]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1 ,activation='sigmoid'))
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
model.fit(x_train , y_train,batch_size=32, epochs = 100,validation_data=(x_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5961 - loss: 0.6814 - val_accuracy: 0.6948 - val_loss: 0.6488
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6466 - loss: 0.6253 - val_accuracy: 0.6818 - val_loss: 0.6012
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6775 - loss: 0.5870 - val_accuracy: 0.7078 - val_loss: 0.5722
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6906 - loss: 0.5609 - val_accuracy: 0.7273 - val_loss: 0.5485
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7117 - loss: 0.5415 - val_accuracy: 0.7532 - val_loss: 0.5315
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7199 - loss: 0.5254 - val_accuracy: 0.7597 - val_loss: 0.5171
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7378 - loss: 0.5124 - val_accuracy: 0.7857 - val_loss: 0.5050
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.5011 - val_accuracy: 0.7922 - val_loss: 0.4959
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4923 - val_accuracy: 0.7922 - val_loss: 0.4880
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4842 - val_accuracy: 0.8182 - val_loss: 0.4812
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4773 - val_accuracy: 0.8117 - val_loss: 0.4751
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4716 - val_accuracy: 0.8117 - val_loss: 0.4705
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4674 - val_accuracy: 0.8117 - val_loss: 0.4674
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4638 - val_accuracy: 0.8117 - val_loss: 0.4660
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4610 - val_accuracy: 0.8117 - val_loss: 0.4642
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4582 - val_accuracy: 0.7987 - val_loss: 0.4621
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4560 - val_accuracy: 0.7922 - val_loss: 0.4604
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4536 - val_accuracy: 0.7922 - val_loss: 0.4593
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4518 - val_accuracy: 0.8052 - val_loss: 0.4594
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4505 - val_accuracy: 0.8117 - val_loss: 0.4583
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4491 - val_accuracy: 0.8117 - val_loss: 0.4583
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4476 - val_accuracy: 0.8117 - val_loss: 0.4574
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4465 - val_accuracy: 0.8052 - val_loss: 0.4585
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4457 - val_accuracy: 0.8052 - val_loss: 0.4587
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4448 - val_accuracy: 0.8052 - val_loss: 0.4593
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4440 - val_accuracy: 0.8052 - val_loss: 0.4589
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4434 - val_accuracy: 0.8052 - val_loss: 0.4606
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4423 - val_accuracy: 0.8052 - val_loss: 0.4607
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4421 - val_accuracy: 0.7987 - val_loss: 0.4609
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4412 - val_accuracy: 0.7987 - val_loss: 0.4606
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4404 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4396 - val_accuracy: 0.7987 - val_loss: 0.4603
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4392 - val_accuracy: 0.8052 - val_loss: 0.4608
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4387 - val_accuracy: 0.8052 - val_loss: 0.4594
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4385 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4375 - val_accuracy: 0.7987 - val_loss: 0.4604
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4370 - val_accuracy: 0.7922 - val_loss: 0.4602
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4359 - val_accuracy: 0.7922 - val_loss: 0.4608
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4353 - val_accuracy: 0.7922 - val_loss: 0.4607
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4350 - val_accuracy: 0.7987 - val_loss: 0.4609
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4347 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4341 - val_accuracy: 0.7922 - val_loss: 0.4599
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4345 - val_accuracy: 0.7922 - val_loss: 0.4610
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4330 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4333 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4325 - val_accuracy: 0.7987 - val_loss: 0.4617
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4319 - val_accuracy: 0.8052 - val_loss: 0.4601
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4316 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4311 - val_accuracy: 0.7922 - val_loss: 0.4614
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4307 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4309 - val_accuracy: 0.7922 - val_loss: 0.4601
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4296 - val_accuracy: 0.7987 - val_loss: 0.4617
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4293 - val_accuracy: 0.7922 - val_loss: 0.4613
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4289 - val_accuracy: 0.7922 - val_loss: 0.4609
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4286 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4282 - val_accuracy: 0.7922 - val_loss: 0.4611
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4279 - val_accuracy: 0.7987 - val_loss: 0.4607
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4274 - val_accuracy: 0.7987 - val_loss: 0.4607
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4272 - val_accuracy: 0.7922 - val_loss: 0.4606
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4267 - val_accuracy: 0.7922 - val_loss: 0.4609
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4264 - val_accuracy: 0.7987 - val_loss: 0.4612
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4266 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4268 - val_accuracy: 0.7987 - val_loss: 0.4620
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4257 - val_accuracy: 0.7987 - val_loss: 0.4621
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4251 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4251 - val_accuracy: 0.7987 - val_loss: 0.4622
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4250 - val_accuracy: 0.7922 - val_loss: 0.4627
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4245 - val_accuracy: 0.7987 - val_loss: 0.4627
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4243 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4236 - val_accuracy: 0.7987 - val_loss: 0.4638
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4247 - val_accuracy: 0.7987 - val_loss: 0.4630
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4235 - val_accuracy: 0.7987 - val_loss: 0.4636
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4235 - val_accuracy: 0.7922 - val_loss: 0.4638
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4229 - val_accuracy: 0.7922 - val_loss: 0.4635
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4223 - val_accuracy: 0.7987 - val_loss: 0.4640
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4221 - val_accuracy: 0.7922 - val_loss: 0.4642
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4218 - val_accuracy: 0.7922 - val_loss: 0.4646
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4217 - val_accuracy: 0.7987 - val_loss: 0.4637
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4211 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4211 - val_accuracy: 0.7922 - val_loss: 0.4627
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4211 - val_accuracy: 0.7922 - val_loss: 0.4624
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4205 - val_accuracy: 0.7922 - val_loss: 0.4627
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4202 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4197 - val_accuracy: 0.7922 - val_loss: 0.4624
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4196 - val_accuracy: 0.7857 - val_loss: 0.4621
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4196 - val_accuracy: 0.7922 - val_loss: 0.4629
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4191 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4196 - val_accuracy: 0.7857 - val_loss: 0.4621
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4184 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4186 - val_accuracy: 0.7922 - val_loss: 0.4620
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4181 - val_accuracy: 0.7857 - val_loss: 0.4617
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4172 - val_accuracy: 0.7922 - val_loss: 0.4619
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4173 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4170 - val_accuracy: 0.7987 - val_loss: 0.4636
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4170 - val_accuracy: 0.7922 - val_loss: 0.4623
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4160 - val_accuracy: 0.7792 - val_loss: 0.4625
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4170 - val_accuracy: 0.7857 - val_loss: 0.4618
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4161 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4155 - val_accuracy: 0.7987 - val_loss: 0.4624
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4151 - val_accuracy: 0.7987 - val_loss: 0.4623

# 1)how to select appropriate optimizer
# 2)no,of nodes in a layer
# 3)how to select no of layers
#4)all in one model

In [16]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 6.7 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [17]:
import kerastuner as kt

/tmp/ipykernel_3064/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [18]:
def build_model(hp):
    model = Sequential()
    model.add(Dense(32, activation="relu", input_dim=8))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer=hp.Choice('optimizer', values=['adam','sgd','rmsprop','adadelta']),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [19]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials = 5)
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

In [20]:
tuner.search(x_train,y_train,epochs = 5,validation_data = (x_test,y_test))
tuner.results_summary()

Trial 4 Complete [00h 00m 03s]
val_accuracy: 0.7467532753944397

Best val_accuracy So Far: 0.7792207598686218
Total elapsed time: 00h 00m 19s
Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 2 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7792207598686218

Trial 3 summary
Hyperparameters:
optimizer: adam
Score: 0.7467532753944397

Trial 1 summary
Hyperparameters:
optimizer: sgd
Score: 0.6948052048683167

Trial 0 summary
Hyperparameters:
optimizer: adadelta
Score: 0.5584415793418884

In [21]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [22]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(x_test,y_test) )

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7622 - loss: 0.5238 - val_accuracy: 0.7922 - val_loss: 0.5093
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.5074 - val_accuracy: 0.7857 - val_loss: 0.4969
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7687 - loss: 0.4974 - val_accuracy: 0.7792 - val_loss: 0.4895
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4895 - val_accuracy: 0.7727 - val_loss: 0.4845
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4836 - val_accuracy: 0.7857 - val_loss: 0.4798
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4782 - val_accuracy: 0.7857 - val_loss: 0.4758
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4738 - val_accuracy: 0.7857 - val_loss: 0.4727
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4700 - val_accuracy: 0.7922 - val_loss: 0.4699
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4673 - val_accuracy: 0.7922 - val_loss: 0.4682
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4643 - val_accuracy: 0.7922 - val_loss: 0.4670
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4623 - val_accuracy: 0.7922 - val_loss: 0.4663
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4603 - val_accuracy: 0.7857 - val_loss: 0.4663
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4587 - val_accuracy: 0.7857 - val_loss: 0.4654
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4571 - val_accuracy: 0.7857 - val_loss: 0.4657
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7769 - loss: 0.4559 - val_accuracy: 0.7857 - val_loss: 0.4652
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7785 - loss: 0.4546 - val_accuracy: 0.7857 - val_loss: 0.4647
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7785 - loss: 0.4533 - val_accuracy: 0.7857 - val_loss: 0.4643
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7785 - loss: 0.4525 - val_accuracy: 0.7857 - val_loss: 0.4644
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7801 - loss: 0.4515 - val_accuracy: 0.7857 - val_loss: 0.4638
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7801 - loss: 0.4509 - val_accuracy: 0.7857 - val_loss: 0.4643
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7785 - loss: 0.4496 - val_accuracy: 0.7857 - val_loss: 0.4639
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7769 - loss: 0.4491 - val_accuracy: 0.7857 - val_loss: 0.4632
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7785 - loss: 0.4485 - val_accuracy: 0.7857 - val_loss: 0.4630
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7769 - loss: 0.4479 - val_accuracy: 0.7857 - val_loss: 0.4637
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7785 - loss: 0.4471 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7801 - loss: 0.4465 - val_accuracy: 0.7922 - val_loss: 0.4642
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7801 - loss: 0.4460 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.7785 - loss: 0.4453 - val_accuracy: 0.7922 - val_loss: 0.4637
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7801 - loss: 0.4449 - val_accuracy: 0.7922 - val_loss: 0.4627
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7801 - loss: 0.4444 - val_accuracy: 0.7922 - val_loss: 0.4630
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7850 - loss: 0.4438 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7834 - loss: 0.4433 - val_accuracy: 0.7922 - val_loss: 0.4627
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7850 - loss: 0.4425 - val_accuracy: 0.8052 - val_loss: 0.4621
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7769 - loss: 0.4421 - val_accuracy: 0.7987 - val_loss: 0.4620
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7818 - loss: 0.4415 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7801 - loss: 0.4412 - val_accuracy: 0.7922 - val_loss: 0.4619
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7834 - loss: 0.4411 - val_accuracy: 0.8052 - val_loss: 0.4614
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7801 - loss: 0.4405 - val_accuracy: 0.8052 - val_loss: 0.4604
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7785 - loss: 0.4401 - val_accuracy: 0.8052 - val_loss: 0.4606
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7801 - loss: 0.4399 - val_accuracy: 0.8052 - val_loss: 0.4603
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7785 - loss: 0.4394 - val_accuracy: 0.8052 - val_loss: 0.4608
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7801 - loss: 0.4390 - val_accuracy: 0.8052 - val_loss: 0.4604
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4383 - val_accuracy: 0.8052 - val_loss: 0.4606
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4383 - val_accuracy: 0.8052 - val_loss: 0.4604
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4376 - val_accuracy: 0.8052 - val_loss: 0.4604
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4371 - val_accuracy: 0.8117 - val_loss: 0.4602
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4368 - val_accuracy: 0.8052 - val_loss: 0.4604
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4367 - val_accuracy: 0.8182 - val_loss: 0.4606
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4360 - val_accuracy: 0.8182 - val_loss: 0.4604
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4358 - val_accuracy: 0.8182 - val_loss: 0.4595
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4354 - val_accuracy: 0.8182 - val_loss: 0.4588
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4348 - val_accuracy: 0.8182 - val_loss: 0.4587
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4345 - val_accuracy: 0.8182 - val_loss: 0.4591
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4344 - val_accuracy: 0.8182 - val_loss: 0.4585
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4337 - val_accuracy: 0.8182 - val_loss: 0.4587
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4335 - val_accuracy: 0.8182 - val_loss: 0.4587
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4332 - val_accuracy: 0.8182 - val_loss: 0.4584
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4327 - val_accuracy: 0.8182 - val_loss: 0.4584
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4325 - val_accuracy: 0.8182 - val_loss: 0.4584
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4320 - val_accuracy: 0.8182 - val_loss: 0.4582
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4321 - val_accuracy: 0.8182 - val_loss: 0.4572
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4318 - val_accuracy: 0.8182 - val_loss: 0.4567
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4314 - val_accuracy: 0.8182 - val_loss: 0.4566
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4306 - val_accuracy: 0.8182 - val_loss: 0.4575
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4307 - val_accuracy: 0.8182 - val_loss: 0.4569
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4304 - val_accuracy: 0.8182 - val_loss: 0.4565
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4301 - val_accuracy: 0.8117 - val_loss: 0.4565
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4298 - val_accuracy: 0.8117 - val_loss: 0.4559
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4293 - val_accuracy: 0.8117 - val_loss: 0.4564
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4291 - val_accuracy: 0.8117 - val_loss: 0.4570
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4286 - val_accuracy: 0.8117 - val_loss: 0.4571
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4285 - val_accuracy: 0.8182 - val_loss: 0.4572
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4283 - val_accuracy: 0.8117 - val_loss: 0.4572
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4279 - val_accuracy: 0.8117 - val_loss: 0.4573
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4279 - val_accuracy: 0.8052 - val_loss: 0.4575
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4270 - val_accuracy: 0.8052 - val_loss: 0.4574
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4269 - val_accuracy: 0.8117 - val_loss: 0.4572
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4265 - val_accuracy: 0.8117 - val_loss: 0.4578
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4266 - val_accuracy: 0.8052 - val_loss: 0.4582
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4262 - val_accuracy: 0.8052 - val_loss: 0.4582
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4256 - val_accuracy: 0.8117 - val_loss: 0.4570
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4252 - val_accuracy: 0.8117 - val_loss: 0.4570
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4250 - val_accuracy: 0.8052 - val_loss: 0.4561
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4248 - val_accuracy: 0.8117 - val_loss: 0.4562
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4248 - val_accuracy: 0.8052 - val_loss: 0.4556
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4241 - val_accuracy: 0.8117 - val_loss: 0.4552
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4241 - val_accuracy: 0.8052 - val_loss: 0.4553
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4237 - val_accuracy: 0.8052 - val_loss: 0.4560
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4234 - val_accuracy: 0.8052 - val_loss: 0.4554
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4230 - val_accuracy: 0.8117 - val_loss: 0.4534
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4229 - val_accuracy: 0.8052 - val_loss: 0.4542
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4225 - val_accuracy: 0.8182 - val_loss: 0.4545
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4221 - val_accuracy: 0.8117 - val_loss: 0.4551
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4219 - val_accuracy: 0.8117 - val_loss: 0.4555

In [34]:
def build_model(hp):
  model = Sequential()
  units = hp.Int('units',min_value = 8,max_value=128,step = 8)
  model.add(Dense(units = units,activation='relu',input_dim = 8))
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics = ['accuracy'])
  return model

In [35]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials = 5,
    directory = 'mydir'
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [39]:
tuner.search(x_train,y_train,epochs=5,validation_data = (x_test,y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7337662577629089

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 12s

In [41]:
tuner.results_summary()

Results summary
Results in mydir/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 2 summary
Hyperparameters:
units: 104
Score: 0.7857142686843872

Trial 1 summary
Hyperparameters:
units: 56
Score: 0.7792207598686218

Trial 0 summary
Hyperparameters:
units: 120
Score: 0.7727272510528564

Trial 3 summary
Hyperparameters:
units: 48
Score: 0.7727272510528564

Trial 4 summary
Hyperparameters:
units: 16
Score: 0.7337662577629089

In [42]:
tuner.get_best_hyperparameters()[0].values

{'units': 104}

In [43]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [46]:
model.fit(x_train , y_train,batch_size=32, epochs = 100,initial_epoch=6,validation_data=(x_test,y_test) )

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8241 - loss: 0.4026 - val_accuracy: 0.8247 - val_loss: 0.4696
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4022 - val_accuracy: 0.8247 - val_loss: 0.4677
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.4019 - val_accuracy: 0.8117 - val_loss: 0.4693
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4015 - val_accuracy: 0.8117 - val_loss: 0.4696
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4003 - val_accuracy: 0.7922 - val_loss: 0.4677
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4001 - val_accuracy: 0.8182 - val_loss: 0.4683
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3999 - val_accuracy: 0.8247 - val_loss: 0.4677
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3991 - val_accuracy: 0.8117 - val_loss: 0.4680
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3980 - val_accuracy: 0.8182 - val_loss: 0.4675
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3984 - val_accuracy: 0.8052 - val_loss: 0.4675
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3980 - val_accuracy: 0.8182 - val_loss: 0.4694
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3971 - val_accuracy: 0.8052 - val_loss: 0.4701
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3970 - val_accuracy: 0.8117 - val_loss: 0.4671
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3970 - val_accuracy: 0.8182 - val_loss: 0.4643
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3957 - val_accuracy: 0.8117 - val_loss: 0.4668
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3955 - val_accuracy: 0.8182 - val_loss: 0.4667
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3957 - val_accuracy: 0.8247 - val_loss: 0.4666
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3957 - val_accuracy: 0.8052 - val_loss: 0.4706
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3940 - val_accuracy: 0.7987 - val_loss: 0.4687
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3942 - val_accuracy: 0.8182 - val_loss: 0.4657
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3935 - val_accuracy: 0.8182 - val_loss: 0.4661
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3929 - val_accuracy: 0.8117 - val_loss: 0.4700
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3923 - val_accuracy: 0.8117 - val_loss: 0.4684
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3919 - val_accuracy: 0.8117 - val_loss: 0.4675
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3915 - val_accuracy: 0.8182 - val_loss: 0.4691
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3921 - val_accuracy: 0.8117 - val_loss: 0.4694
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3901 - val_accuracy: 0.8117 - val_loss: 0.4703
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3910 - val_accuracy: 0.7987 - val_loss: 0.4719
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3905 - val_accuracy: 0.8117 - val_loss: 0.4697
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3893 - val_accuracy: 0.8052 - val_loss: 0.4689
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3885 - val_accuracy: 0.8052 - val_loss: 0.4709
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3900 - val_accuracy: 0.8182 - val_loss: 0.4694
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3878 - val_accuracy: 0.8117 - val_loss: 0.4724
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3873 - val_accuracy: 0.8052 - val_loss: 0.4719
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3866 - val_accuracy: 0.8182 - val_loss: 0.4694
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3877 - val_accuracy: 0.8052 - val_loss: 0.4704
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3864 - val_accuracy: 0.8182 - val_loss: 0.4684
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3861 - val_accuracy: 0.8117 - val_loss: 0.4681
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3864 - val_accuracy: 0.8182 - val_loss: 0.4701
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3858 - val_accuracy: 0.8052 - val_loss: 0.4713
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3842 - val_accuracy: 0.8182 - val_loss: 0.4698
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3852 - val_accuracy: 0.8117 - val_loss: 0.4673
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3843 - val_accuracy: 0.8052 - val_loss: 0.4713
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3833 - val_accuracy: 0.8052 - val_loss: 0.4711
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8322 - loss: 0.3829 - val_accuracy: 0.8052 - val_loss: 0.4737
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8322 - loss: 0.3832 - val_accuracy: 0.8117 - val_loss: 0.4718
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8322 - loss: 0.3821 - val_accuracy: 0.7987 - val_loss: 0.4695
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8339 - loss: 0.3824 - val_accuracy: 0.7987 - val_loss: 0.4714
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.3821 - val_accuracy: 0.8117 - val_loss: 0.4723
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8290 - loss: 0.3813 - val_accuracy: 0.8052 - val_loss: 0.4753
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8290 - loss: 0.3806 - val_accuracy: 0.8117 - val_loss: 0.4709
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8290 - loss: 0.3811 - val_accuracy: 0.8117 - val_loss: 0.4712
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8306 - loss: 0.3808 - val_accuracy: 0.8052 - val_loss: 0.4747
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8355 - loss: 0.3793 - val_accuracy: 0.7987 - val_loss: 0.4746
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8355 - loss: 0.3795 - val_accuracy: 0.7987 - val_loss: 0.4741
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3797 - val_accuracy: 0.8052 - val_loss: 0.4759
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3788 - val_accuracy: 0.8052 - val_loss: 0.4737
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3782 - val_accuracy: 0.8052 - val_loss: 0.4728
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3782 - val_accuracy: 0.8052 - val_loss: 0.4737
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3769 - val_accuracy: 0.8117 - val_loss: 0.4704
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3770 - val_accuracy: 0.8052 - val_loss: 0.4739
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3758 - val_accuracy: 0.8052 - val_loss: 0.4719
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3767 - val_accuracy: 0.8182 - val_loss: 0.4747
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3769 - val_accuracy: 0.8117 - val_loss: 0.4752
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3745 - val_accuracy: 0.8052 - val_loss: 0.4752
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3745 - val_accuracy: 0.8117 - val_loss: 0.4761
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3752 - val_accuracy: 0.8052 - val_loss: 0.4753
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3734 - val_accuracy: 0.8052 - val_loss: 0.4749
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3745 - val_accuracy: 0.8052 - val_loss: 0.4761
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3733 - val_accuracy: 0.8052 - val_loss: 0.4756
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3725 - val_accuracy: 0.8052 - val_loss: 0.4758
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3735 - val_accuracy: 0.8117 - val_loss: 0.4755
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3720 - val_accuracy: 0.8052 - val_loss: 0.4754
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3720 - val_accuracy: 0.7987 - val_loss: 0.4774
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3720 - val_accuracy: 0.8117 - val_loss: 0.4773
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3710 - val_accuracy: 0.8052 - val_loss: 0.4752
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3704 - val_accuracy: 0.7987 - val_loss: 0.4780
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3709 - val_accuracy: 0.7987 - val_loss: 0.4771
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8436 - loss: 0.3700 - val_accuracy: 0.7987 - val_loss: 0.4752
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3692 - val_accuracy: 0.7987 - val_loss: 0.4732
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3693 - val_accuracy: 0.8052 - val_loss: 0.4710
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8436 - loss: 0.3691 - val_accuracy: 0.8052 - val_loss: 0.4732
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3684 - val_accuracy: 0.8117 - val_loss: 0.4716
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3677 - val_accuracy: 0.8052 - val_loss: 0.4744
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8453 - loss: 0.3684 - val_accuracy: 0.8052 - val_loss: 0.4784
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3672 - val_accuracy: 0.8117 - val_loss: 0.4783
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8420 - loss: 0.3668 - val_accuracy: 0.7987 - val_loss: 0.4807
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3668 - val_accuracy: 0.8052 - val_loss: 0.4799
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.3663 - val_accuracy: 0.8117 - val_loss: 0.4753
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3656 - val_accuracy: 0.8052 - val_loss: 0.4747
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8420 - loss: 0.3646 - val_accuracy: 0.8117 - val_loss: 0.4751
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3641 - val_accuracy: 0.8117 - val_loss: 0.4745
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3645 - val_accuracy: 0.8182 - val_loss: 0.4744
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3644 - val_accuracy: 0.8117 - val_loss: 0.4754

In [52]:
def build_model(hp):
    model = Sequential()

    model.add(Dense(72, activation="relu", input_dim=8))

    num_layers = hp.Int('num_layers', min_value=1, max_value=10)

    for i in range(num_layers):
        model.add(Dense(72, activation='relu'))

    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer='rmsprop',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [53]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=3,
    directory='mydir',
    project_name="num_layers"
)

In [56]:
 tuner.search(x_train ,y_train,epochs = 5,validation_data =(x_test,y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.798701286315918

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 12s

In [59]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4}

In [60]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [61]:
model.fit(x_train,y_train,batch_size = 32, epochs = 100,initial_epoch = 6, validation_data = (x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - accuracy: 0.7834 - loss: 0.4588 - val_accuracy: 0.7922 - val_loss: 0.4769
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7834 - loss: 0.4414 - val_accuracy: 0.7922 - val_loss: 0.4772
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7818 - loss: 0.4297 - val_accuracy: 0.7922 - val_loss: 0.4652
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4259 - val_accuracy: 0.7987 - val_loss: 0.4717
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4187 - val_accuracy: 0.7727 - val_loss: 0.4700
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4108 - val_accuracy: 0.7922 - val_loss: 0.4710
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4022 - val_accuracy: 0.7922 - val_loss: 0.4667
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3957 - val_accuracy: 0.7662 - val_loss: 0.5116
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3844 - val_accuracy: 0.7792 - val_loss: 0.4840
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3871 - val_accuracy: 0.7987 - val_loss: 0.4845
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3704 - val_accuracy: 0.7857 - val_loss: 0.4836
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3645 - val_accuracy: 0.7792 - val_loss: 0.4671
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3520 - val_accuracy: 0.7857 - val_loss: 0.4925
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3469 - val_accuracy: 0.7727 - val_loss: 0.4777
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3252 - val_accuracy: 0.7727 - val_loss: 0.5449
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3192 - val_accuracy: 0.7987 - val_loss: 0.5187
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3095 - val_accuracy: 0.7403 - val_loss: 0.6964
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.2902 - val_accuracy: 0.7727 - val_loss: 0.5309
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2818 - val_accuracy: 0.7597 - val_loss: 0.5797
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2810 - val_accuracy: 0.7857 - val_loss: 0.5523
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2644 - val_accuracy: 0.8052 - val_loss: 0.5581
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2587 - val_accuracy: 0.7727 - val_loss: 0.5666
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9137 - loss: 0.2360 - val_accuracy: 0.7532 - val_loss: 0.6887
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2288 - val_accuracy: 0.7662 - val_loss: 0.5946
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2179 - val_accuracy: 0.7662 - val_loss: 0.6112
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2239 - val_accuracy: 0.7338 - val_loss: 0.6347
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9316 - loss: 0.1947 - val_accuracy: 0.7403 - val_loss: 0.7380
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1856 - val_accuracy: 0.7662 - val_loss: 0.6612
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1657 - val_accuracy: 0.7857 - val_loss: 0.7703
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1849 - val_accuracy: 0.7468 - val_loss: 0.7077
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1645 - val_accuracy: 0.7208 - val_loss: 1.0594
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9235 - loss: 0.1689 - val_accuracy: 0.7532 - val_loss: 0.7010
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1409 - val_accuracy: 0.7792 - val_loss: 0.7797
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9446 - loss: 0.1357 - val_accuracy: 0.7532 - val_loss: 0.8106
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1256 - val_accuracy: 0.7338 - val_loss: 0.9139
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9528 - loss: 0.1427 - val_accuracy: 0.7208 - val_loss: 1.0001
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9528 - loss: 0.1180 - val_accuracy: 0.7338 - val_loss: 0.9054
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9593 - loss: 0.1091 - val_accuracy: 0.7597 - val_loss: 1.0251
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.0993 - val_accuracy: 0.7468 - val_loss: 1.0884
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9463 - loss: 0.1313 - val_accuracy: 0.7597 - val_loss: 1.0284
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0746 - val_accuracy: 0.7273 - val_loss: 1.3021
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0928 - val_accuracy: 0.7273 - val_loss: 1.5712
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0655 - val_accuracy: 0.6558 - val_loss: 1.4228
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9609 - loss: 0.1052 - val_accuracy: 0.7922 - val_loss: 1.0548
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0697 - val_accuracy: 0.7597 - val_loss: 1.1102
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.0945 - val_accuracy: 0.7403 - val_loss: 1.1813
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0447 - val_accuracy: 0.7273 - val_loss: 1.2349
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0774 - val_accuracy: 0.7662 - val_loss: 1.1747
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0714 - val_accuracy: 0.6818 - val_loss: 1.1814
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.0868 - val_accuracy: 0.7727 - val_loss: 1.1708
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0334 - val_accuracy: 0.7597 - val_loss: 1.3599
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0301 - val_accuracy: 0.6104 - val_loss: 1.9534
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0915 - val_accuracy: 0.7792 - val_loss: 1.2539
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0907 - val_accuracy: 0.7857 - val_loss: 1.3034
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0379 - val_accuracy: 0.7727 - val_loss: 1.3934
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0524 - val_accuracy: 0.7143 - val_loss: 1.3554
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0408 - val_accuracy: 0.7597 - val_loss: 1.3113
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0468 - val_accuracy: 0.7403 - val_loss: 1.3483
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0285 - val_accuracy: 0.7338 - val_loss: 1.5358
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0461 - val_accuracy: 0.7532 - val_loss: 1.5435
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0395 - val_accuracy: 0.7143 - val_loss: 1.5805
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0394 - val_accuracy: 0.7403 - val_loss: 1.7568
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0340 - val_accuracy: 0.6948 - val_loss: 1.7011
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0368 - val_accuracy: 0.7987 - val_loss: 1.5114
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0191 - val_accuracy: 0.7727 - val_loss: 1.6195
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0136 - val_accuracy: 0.7468 - val_loss: 2.1952
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.0868 - val_accuracy: 0.7662 - val_loss: 1.6266
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0178 - val_accuracy: 0.7468 - val_loss: 1.6872
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0303 - val_accuracy: 0.7727 - val_loss: 1.6152
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.1008 - val_accuracy: 0.7922 - val_loss: 1.5404
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0115 - val_accuracy: 0.7662 - val_loss: 1.6118
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9967 - loss: 0.0109 - val_accuracy: 0.7403 - val_loss: 1.7013
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9853 - loss: 0.0384 - val_accuracy: 0.7532 - val_loss: 1.7151
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9919 - loss: 0.0225 - val_accuracy: 0.7662 - val_loss: 1.6033
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9967 - loss: 0.0086 - val_accuracy: 0.7597 - val_loss: 1.8138
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9821 - loss: 0.0590 - val_accuracy: 0.6234 - val_loss: 2.2491
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9837 - loss: 0.0455 - val_accuracy: 0.7208 - val_loss: 1.7731
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9886 - loss: 0.0329 - val_accuracy: 0.7338 - val_loss: 1.8225
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9919 - loss: 0.0197 - val_accuracy: 0.7273 - val_loss: 2.0670
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9886 - loss: 0.0254 - val_accuracy: 0.7403 - val_loss: 2.3796
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9902 - loss: 0.0361 - val_accuracy: 0.7403 - val_loss: 1.9305
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.7403 - val_loss: 2.1218
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0235 - val_accuracy: 0.7468 - val_loss: 1.8779
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0150 - val_accuracy: 0.7662 - val_loss: 2.1198
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0424 - val_accuracy: 0.7532 - val_loss: 1.9771
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0097 - val_accuracy: 0.7532 - val_loss: 2.3974
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0417 - val_accuracy: 0.7532 - val_loss: 1.8301
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0434 - val_accuracy: 0.7208 - val_loss: 1.9322
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0095 - val_accuracy: 0.7403 - val_loss: 1.8805
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0046 - val_accuracy: 0.7208 - val_loss: 1.9113
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0142 - val_accuracy: 0.7468 - val_loss: 1.9477
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0207 - val_accuracy: 0.7532 - val_loss: 2.3916
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0501 - val_accuracy: 0.7532 - val_loss: 2.0410
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0070 - val_accuracy: 0.7338 - val_loss: 2.0046

In [62]:
def build_model(hp):
    model = Sequential()

    # Number of hidden layers
    num_layers = hp.Int('num_layers', min_value=1, max_value=5)

    for i in range(num_layers):
        units = hp.Int(f'units_{i}', min_value=8, max_value=128, step=8)
        activation = hp.Choice(f'activation_{i}', values=['relu', 'tanh', 'sigmoid'])

        if i == 0:
            model.add(Dense(units=units, activation=activation, input_dim=8))
        else:
            model.add(Dense(units=units, activation=activation))

    # Output layer
    model.add(Dense(1, activation="sigmoid"))

    # Compile
    model.compile(
        optimizer=hp.Choice('optimizer', values=['rmsprop', 'adam', 'sgd', 'nadam', 'adadelta']),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [63]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 3,
                        directory = 'mydir',
                        project_name = 'final'
                        )

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [64]:
tuner.search(x_train,y_train,epochs = 5,validation_data = (x_test,y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.3571428656578064

Best val_accuracy So Far: 0.649350643157959
Total elapsed time: 00h 00m 08s

In [65]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units_0': 24,
 'activation_0': 'relu',
 'optimizer': 'sgd',
 'units_1': 8,
 'activation_1': 'relu',
 'units_2': 8,
 'activation_2': 'relu'}

In [66]:
model=tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [68]:
model.fit(x_train , y_train,epochs = 200,initial_epoch=6,validation_data = (x_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.6759 - loss: 0.6575 - val_accuracy: 0.6494 - val_loss: 0.6620
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6775 - loss: 0.6522 - val_accuracy: 0.6494 - val_loss: 0.6566
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6775 - loss: 0.6465 - val_accuracy: 0.6429 - val_loss: 0.6513
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6726 - loss: 0.6411 - val_accuracy: 0.6364 - val_loss: 0.6467
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6661 - loss: 0.6363 - val_accuracy: 0.6429 - val_loss: 0.6423
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6629 - loss: 0.6317 - val_accuracy: 0.6494 - val_loss: 0.6382
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6612 - loss: 0.6275 - val_accuracy: 0.6494 - val_loss: 0.6339
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6629 - loss: 0.6230 - val_accuracy: 0.6494 - val_loss: 0.6294
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6629 - loss: 0.6185 - val_accuracy: 0.6494 - val_loss: 0.6256
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6612 - loss: 0.6146 - val_accuracy: 0.6494 - val_loss: 0.6218
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6629 - loss: 0.6111 - val_accuracy: 0.6494 - val_loss: 0.6178
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6629 - loss: 0.6072 - val_accuracy: 0.6494 - val_loss: 0.6138
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6645 - loss: 0.6032 - val_accuracy: 0.6494 - val_loss: 0.6099
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6678 - loss: 0.5993 - val_accuracy: 0.6494 - val_loss: 0.6061
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6678 - loss: 0.5955 - val_accuracy: 0.6494 - val_loss: 0.6027
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6694 - loss: 0.5921 - val_accuracy: 0.6558 - val_loss: 0.5989
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6678 - loss: 0.5885 - val_accuracy: 0.6623 - val_loss: 0.5950
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6694 - loss: 0.5846 - val_accuracy: 0.6623 - val_loss: 0.5910
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6775 - loss: 0.5806 - val_accuracy: 0.6688 - val_loss: 0.5871
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6792 - loss: 0.5770 - val_accuracy: 0.6753 - val_loss: 0.5834
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6824 - loss: 0.5733 - val_accuracy: 0.7013 - val_loss: 0.5790
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6954 - loss: 0.5691 - val_accuracy: 0.7013 - val_loss: 0.5748
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7020 - loss: 0.5654 - val_accuracy: 0.7013 - val_loss: 0.5708
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7036 - loss: 0.5614 - val_accuracy: 0.7013 - val_loss: 0.5669
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5575 - val_accuracy: 0.7078 - val_loss: 0.5624
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7150 - loss: 0.5534 - val_accuracy: 0.7078 - val_loss: 0.5583
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7150 - loss: 0.5495 - val_accuracy: 0.7013 - val_loss: 0.5542
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7150 - loss: 0.5458 - val_accuracy: 0.7078 - val_loss: 0.5499
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7215 - loss: 0.5420 - val_accuracy: 0.7143 - val_loss: 0.5458
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5384 - val_accuracy: 0.7208 - val_loss: 0.5416
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7264 - loss: 0.5347 - val_accuracy: 0.7273 - val_loss: 0.5382
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7264 - loss: 0.5314 - val_accuracy: 0.7208 - val_loss: 0.5346
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7280 - loss: 0.5282 - val_accuracy: 0.7273 - val_loss: 0.5310
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7264 - loss: 0.5248 - val_accuracy: 0.7273 - val_loss: 0.5271
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7264 - loss: 0.5214 - val_accuracy: 0.7403 - val_loss: 0.5242
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7264 - loss: 0.5184 - val_accuracy: 0.7468 - val_loss: 0.5212
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7280 - loss: 0.5156 - val_accuracy: 0.7532 - val_loss: 0.5185
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5130 - val_accuracy: 0.7597 - val_loss: 0.5159
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7313 - loss: 0.5107 - val_accuracy: 0.7597 - val_loss: 0.5130
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7329 - loss: 0.5080 - val_accuracy: 0.7532 - val_loss: 0.5102
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7362 - loss: 0.5054 - val_accuracy: 0.7597 - val_loss: 0.5073
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.5029 - val_accuracy: 0.7662 - val_loss: 0.5051
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.5010 - val_accuracy: 0.7662 - val_loss: 0.5028
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.4988 - val_accuracy: 0.7662 - val_loss: 0.5003
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.4967 - val_accuracy: 0.7727 - val_loss: 0.4980
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.4948 - val_accuracy: 0.7727 - val_loss: 0.4963
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7427 - loss: 0.4930 - val_accuracy: 0.7727 - val_loss: 0.4943
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7492 - loss: 0.4915 - val_accuracy: 0.7792 - val_loss: 0.4928
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7541 - loss: 0.4898 - val_accuracy: 0.7922 - val_loss: 0.4912
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.4883 - val_accuracy: 0.7922 - val_loss: 0.4893
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.4867 - val_accuracy: 0.7987 - val_loss: 0.4877
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4852 - val_accuracy: 0.7987 - val_loss: 0.4866
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.4839 - val_accuracy: 0.7987 - val_loss: 0.4850
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4824 - val_accuracy: 0.7987 - val_loss: 0.4832
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4813 - val_accuracy: 0.7987 - val_loss: 0.4821
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4800 - val_accuracy: 0.8052 - val_loss: 0.4810
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4789 - val_accuracy: 0.8117 - val_loss: 0.4800
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4779 - val_accuracy: 0.8052 - val_loss: 0.4786
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4766 - val_accuracy: 0.8052 - val_loss: 0.4773
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4758 - val_accuracy: 0.8052 - val_loss: 0.4765
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4748 - val_accuracy: 0.8052 - val_loss: 0.4753
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4737 - val_accuracy: 0.8052 - val_loss: 0.4743
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4726 - val_accuracy: 0.8052 - val_loss: 0.4732
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4716 - val_accuracy: 0.8052 - val_loss: 0.4722
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4708 - val_accuracy: 0.8117 - val_loss: 0.4717
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4700 - val_accuracy: 0.8117 - val_loss: 0.4707
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4691 - val_accuracy: 0.8052 - val_loss: 0.4698
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4686 - val_accuracy: 0.8052 - val_loss: 0.4690
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4677 - val_accuracy: 0.8052 - val_loss: 0.4686
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4671 - val_accuracy: 0.8052 - val_loss: 0.4678
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4665 - val_accuracy: 0.8052 - val_loss: 0.4673
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4658 - val_accuracy: 0.8117 - val_loss: 0.4666
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4650 - val_accuracy: 0.8117 - val_loss: 0.4661
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4644 - val_accuracy: 0.8117 - val_loss: 0.4661
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4637 - val_accuracy: 0.8117 - val_loss: 0.4655
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4631 - val_accuracy: 0.8182 - val_loss: 0.4652
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4626 - val_accuracy: 0.8182 - val_loss: 0.4648
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4620 - val_accuracy: 0.8117 - val_loss: 0.4647
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4615 - val_accuracy: 0.8117 - val_loss: 0.4641
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4611 - val_accuracy: 0.8182 - val_loss: 0.4636
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4605 - val_accuracy: 0.8117 - val_loss: 0.4628
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4597 - val_accuracy: 0.8182 - val_loss: 0.4624
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4593 - val_accuracy: 0.8117 - val_loss: 0.4616
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4586 - val_accuracy: 0.8182 - val_loss: 0.4613
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4583 - val_accuracy: 0.8182 - val_loss: 0.4610
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4578 - val_accuracy: 0.8247 - val_loss: 0.4607
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4572 - val_accuracy: 0.8247 - val_loss: 0.4605
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4568 - val_accuracy: 0.8247 - val_loss: 0.4597
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4563 - val_accuracy: 0.8182 - val_loss: 0.4592
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4556 - val_accuracy: 0.8247 - val_loss: 0.4595
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4552 - val_accuracy: 0.8182 - val_loss: 0.4590
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4548 - val_accuracy: 0.8247 - val_loss: 0.4589
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4545 - val_accuracy: 0.8182 - val_loss: 0.4586
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4540 - val_accuracy: 0.8182 - val_loss: 0.4578
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4536 - val_accuracy: 0.8182 - val_loss: 0.4578
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4532 - val_accuracy: 0.8182 - val_loss: 0.4578
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4528 - val_accuracy: 0.8182 - val_loss: 0.4577
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4525 - val_accuracy: 0.8247 - val_loss: 0.4576
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4519 - val_accuracy: 0.8247 - val_loss: 0.4573
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4515 - val_accuracy: 0.8182 - val_loss: 0.4569
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4511 - val_accuracy: 0.8182 - val_loss: 0.4567
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4511 - val_accuracy: 0.8182 - val_loss: 0.4565
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4504 - val_accuracy: 0.8182 - val_loss: 0.4563
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4501 - val_accuracy: 0.8247 - val_loss: 0.4563
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4497 - val_accuracy: 0.8052 - val_loss: 0.4573
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4495 - val_accuracy: 0.8117 - val_loss: 0.4567
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4492 - val_accuracy: 0.8117 - val_loss: 0.4567
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4486 - val_accuracy: 0.8182 - val_loss: 0.4568
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4480 - val_accuracy: 0.8182 - val_loss: 0.4569
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4478 - val_accuracy: 0.8182 - val_loss: 0.4568
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4473 - val_accuracy: 0.8247 - val_loss: 0.4572
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4471 - val_accuracy: 0.8377 - val_loss: 0.4568
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4469 - val_accuracy: 0.8312 - val_loss: 0.4561
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4465 - val_accuracy: 0.8182 - val_loss: 0.4555
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4461 - val_accuracy: 0.8247 - val_loss: 0.4558
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4458 - val_accuracy: 0.8377 - val_loss: 0.4568
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4452 - val_accuracy: 0.8247 - val_loss: 0.4564
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4447 - val_accuracy: 0.8247 - val_loss: 0.4559
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4447 - val_accuracy: 0.8247 - val_loss: 0.4553
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4442 - val_accuracy: 0.8247 - val_loss: 0.4554
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4440 - val_accuracy: 0.8247 - val_loss: 0.4555
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4435 - val_accuracy: 0.8247 - val_loss: 0.4550
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4431 - val_accuracy: 0.8247 - val_loss: 0.4541
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4428 - val_accuracy: 0.8247 - val_loss: 0.4543
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4425 - val_accuracy: 0.8247 - val_loss: 0.4546
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4425 - val_accuracy: 0.8247 - val_loss: 0.4547
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4418 - val_accuracy: 0.8247 - val_loss: 0.4541
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4417 - val_accuracy: 0.8182 - val_loss: 0.4540
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4413 - val_accuracy: 0.8247 - val_loss: 0.4540
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4410 - val_accuracy: 0.8247 - val_loss: 0.4540
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4406 - val_accuracy: 0.8247 - val_loss: 0.4541
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4406 - val_accuracy: 0.8247 - val_loss: 0.4541
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4402 - val_accuracy: 0.8247 - val_loss: 0.4542
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4399 - val_accuracy: 0.8247 - val_loss: 0.4539
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4396 - val_accuracy: 0.8247 - val_loss: 0.4539
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4392 - val_accuracy: 0.8247 - val_loss: 0.4538
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4391 - val_accuracy: 0.8247 - val_loss: 0.4535
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4386 - val_accuracy: 0.8247 - val_loss: 0.4540
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4384 - val_accuracy: 0.8247 - val_loss: 0.4542
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4382 - val_accuracy: 0.8247 - val_loss: 0.4537
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4378 - val_accuracy: 0.8247 - val_loss: 0.4540
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4374 - val_accuracy: 0.8247 - val_loss: 0.4535
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4374 - val_accuracy: 0.8247 - val_loss: 0.4534
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4371 - val_accuracy: 0.8247 - val_loss: 0.4533
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4366 - val_accuracy: 0.8247 - val_loss: 0.4536
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4365 - val_accuracy: 0.8247 - val_loss: 0.4532
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4362 - val_accuracy: 0.8247 - val_loss: 0.4537
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4360 - val_accuracy: 0.8247 - val_loss: 0.4534
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4355 - val_accuracy: 0.8247 - val_loss: 0.4526
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4352 - val_accuracy: 0.8247 - val_loss: 0.4529
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4354 - val_accuracy: 0.8247 - val_loss: 0.4521
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4349 - val_accuracy: 0.8247 - val_loss: 0.4519
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4343 - val_accuracy: 0.8247 - val_loss: 0.4519
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4341 - val_accuracy: 0.8182 - val_loss: 0.4522
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4335 - val_accuracy: 0.8247 - val_loss: 0.4523
Epoch 162/200